MODEL:
  RPTM_SELECT: "mean"

INPUT:
  HEIGHT: 224
  WIDTH: 224
  # TODO: mean and std of specific datasets

DATASET:
  NAME: "veri"

SOLVER:
  OPTIMIZER: "adam"
  EPOCHS: 50
  BASE_LR: 0.005
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  BATCH_SIZE: 8
  AMP: False

LOSS:
  MARGIN: 1.0
  LAMBDA_CE: 1.0
  LAMBDA_TRI: 1.0

TEST:
  BATCH_SIZE: 24

MISC:
  LOG_DIR: "./logs/veri/"
