MODEL:
  ARCH: "resnet50"
  TWO_BRANCH: True

INPUT:
  HEIGHT: 128
  WIDTH: 128
  AUGMENT: True
  FLIP_PROB: 0.5
  RAND_ERASE: True
  MEAN: [0.4190, 0.4185, 0.4260]
  STD: [0.1897, 0.1883, 0.1880]

DATASET:
  NAME: "veri"

SOLVER:
  OPTIMIZER: "adamw"
  EPOCHS: 50
  BASE_LR: 0.005
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  BATCH_SIZE: 16
  AMP: False

LOSS:
  MARGIN: 1.0
  LAMBDA_CE: 1.0
  LAMBDA_TRI: 1.0

TEST:
  BATCH_SIZE: 48

MISC:
  LOG_DIR: "./logs/veri/"
