MODEL:
  ARCH: "resnet101"
  TWO_BRANCH: True

INPUT:
  HEIGHT: 160
  WIDTH: 160
  AUGMENT: True
  FLIP_PROB: 0.5
  RAND_ERASE: True
  MEAN: [0.4822, 0.4821, 0.4899]
  STD: [0.1994, 0.1982, 0.2063]

DATASET:
  NAME: "vric"

SOLVER:
  OPTIMIZER: "adamw"
  EPOCHS: 56
  BASE_LR: 0.00015
  WEIGHT_DECAY: 0.0005
  DECAY_BN_BIAS: False
  BATCH_SIZE: 16

LOSS:
  MARGIN: 1.0
  LAMBDA_CE: 2.0
  LAMBDA_TRI: 1.0

TEST:
  BATCH_SIZE: 48

MISC:
  LOG_DIR: "./logs/vric"
  SEED: 1502687543
  SAVE_FREQ: 10
